### ISSUE TITLE
Error: Query inactivity timeout

### ISSUE THREAD

**Issue by mauvm** [kukua/node-concava-adapter-mysql#2]
```
{ [Error: Error: Query inactivity timeout] statusCode: 400 }
Error: Error: Query inactivity timeout
    at setMetadata.js:7:11
    at /data/node_modules/concava-adapter-mysql/lib/adapter.js:91:19
    at /data/node_modules/concava-adapter-mysql/node_modules/async-waterfall/index.js:47:20
    at handler (/data/node_modules/concava-adapter-mysql/node_modules/map-async/index.js:30:36)
    at Query._callback (/data/node_modules/concava-adapter-mysql/lib/adapter.js:150:20)
    at Query.Sequence.end (/data/node_modules/concava-adapter-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at /data/node_modules/concava-adapter-mysql/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /data/node_modules/concava-adapter-mysql/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at doNTCallback0 (node.js:417:9)
```

Keeps occuring in `concava-adapter-mysql@0.3`.

**Comment by mauvm** [comment]
This appeared to be the problem: https://github.com/felixge/node-mysql/issues/1236.
No timeouts after updating to Node v5.11.
